local_costmap:
#  footprint: [[-0.15,-0.15],[-0.15,0.15],[0.15, 0.15],[0.3, 0],[0.15,-0.15]]
#  footprint: circle

  robot_radius: 0.15
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: true
  rolling_window: true
  width: 2
  height: 2
  resolution: 0.05
  transform_tolerance: 1.0
  inflation_radius: 0.1
  map_type: costmap
  
