global_costmap:
  footprint: [[-0.2,-0.2],[-0.2,0.2],[0.2, 0.2],[0.3, 0],[0.2,-0.2]]
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0  ##
  static_map: true
  rolling_window: false
  resolution: 0.05
  transform_tolerance: 1.0
  cost_scaling_factor:  10   ###47
  inflation_radius: 50   ##37.5   ##20
  map_type: costmap


